add_newline = false

format = """
$git_branch\
$git_status\
$rust\
$golang\
$docker_context\
$kubernetes
$os [$username](yellow) $directory$character
"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[username]
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style)"

[directory]
read_only = " "

[docker_context]
symbol = " "
format = "[$symbol$context]($style)"

[golang]
symbol = " "
format = "[$symbol($version )]($style)"

[hg_branch]
symbol = " "

[memory_usage]
symbol = " "

[os]
disabled = false

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "
format = "[$symbol($version )]($style)"

